openapi: 3.0.1
info:
  title: General
  version: general
  x-file-name: general
  description: |
    In this section:
      - [WB API general information](/openapi/api-information#tag/Introduction)
      - how to [get started with the WB API](/openapi/api-information#tag/Introduction/How-to-get-started-with-the-API)
      - how to [log in](/openapi/api-information#tag/Authorization) and [create tokens](/openapi/api-information#tag/Authorization/How-to-create-a-personal-access-base-or-test-token)
      - main [HTTP status codes](/openapi/api-information#tag/Introduction/HTTP-status-codes)
      - [rate limits](/openapi/api-information#tag/Introduction/Rate-Limits)
      - how to contact [support](/openapi/api-information#tag/Introduction/Support)

    Use the methods in this section to:
      - check the [WB API connection](/openapi/api-information#tag/WB-API-Connection-Check)
      - get [seller portal news](/openapi/api-information#tag/News-API/paths/~1api~1communications~1v2~1news/get)
      - get [seller information](/openapi/api-information#tag/Seller-Information)
      - [manage seller users](/openapi/api-information#tag/Seller-User-Management)
security:
  - HeaderApiKey: []
tags:
  - name: Introduction
    description: ''
  - name: Authorization
    description: ''
  - name: WB API Connection Check
    description: ''
  - name: News API
    description: ''
  - name: Seller Information
    description: ''
  - name: Seller User Management
    description: ''
paths:
  /ping:
    servers:
      - url: https://common-api.wildberries.ru
    get:
      x-readonly-method: true
      x-category: all
      tags:
        - WB API Connection Check
      security:
        - HeaderApiKey: []
      summary: Connection Check
      description: |
        Checks:
          1. Whether the request successfully reaches the WB API.
          2. The validity of the authorization token and request URL.
          3. Whether the token category matches the service.

        <div class="description_important">
          This method is not intended to check the availability of WB services
        </div>

        Each service has its own version of the method depending on the domain:

        | Category | Request URL |
        |---------------|-----------------------|
        | Content | `https://content-api.wildberries.ru/ping`<br>`https://content-api-sandbox.wildberries.ru/ping` |
        | Analytics | `https://seller-analytics-api.wildberries.ru/ping` |
        | Prices and Discounts | `https://discounts-prices-api.wildberries.ru/ping`<br>`https://discounts-prices-api-sandbox.wildberries.ru/ping` |
        | Marketplace | `https://marketplace-api.wildberries.ru/ping` |
        | Statistics | `https://statistics-api.wildberries.ru/ping`<br>`https://statistics-api-sandbox.wildberries.ru/ping` |
        | Promotion | `https://advert-api.wildberries.ru/ping`<br>`https://advert-api-sandbox.wildberries.ru/ping` |
        | Feedbacks and Questions | `https://feedbacks-api.wildberries.ru/ping`<br>`https://feedbacks-api-sandbox.wildberries.ru/ping` |
        | Buyers Chat | `https://buyer-chat-api.wildberries.ru/ping` |
        | Supplies | `https://supplies-api.wildberries.ru/ping` |
        | Buyers Returns | `https://returns-api.wildberries.ru/ping` |
        | Documents | `https://documents-api.wildberries.ru/ping` |
        | Finance | `https://finance-api.wildberries.ru/ping` |
        | Tariffs, News, Seller Information | `https://common-api.wildberries.ru/ping` |
        | Seller User Management | `https://user-management-api.wildberries.ru/ping` |

        <div class="description_limit">
          A maximum of 3 requests every 30 <a href="/openapi/api-information#tag/Introduction/Rate-Limits">seconds</a>. If you try to use this method programmatically, the method will be temporarily blocked. The rate limit applies individually to each instance of the method on each host
        </div>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  TS:
                    type: string
                    description: Request timestamp
                  Status:
                    type: string
                    enum:
                      - OK
                    description: Status
              example:
                TS: '2024-08-16T11:19:05+03:00'
                Status: OK
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
  /api/communications/v2/news:
    servers:
      - url: https://common-api.wildberries.ru
    get:
      x-readonly-method: true
      x-category: commonapi
      tags:
        - News API
      security:
        - HeaderApiKey: []
      summary: Getting Seller Portal News
      description: |
        The method allows getting news from the seller portal.
        <br> To receive a successful response, one of the parameters `from` or `fromID` must be specified.
        <br> You can get up to 100 news items per request.

        <div class="description_limit">
        <a href="/openapi/api-information#tag/Introduction/Rate-Limits">Request limit</a> per one seller's account:

        | Period | Limit | Interval | Burst |
        | --- | --- | --- | --- |
        | 1 minute | 1 request | 1 minute | 10 requests |
        </div>
      parameters:
        - in: query
          name: from
          required: false
          schema:
            type: string
            format: date
            description: Date from which to get news
            example: '2025-02-06'
        - in: query
          name: fromID
          required: false
          schema:
            type: integer
            format: uint64
          description: The news ID, starting from which — including it — you need to get the list of news
          example: 7369
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    description: News data
                    items:
                      type: object
                      properties:
                        content:
                          type: string
                          description: News text
                          format: plaintext
                        date:
                          format: date-time
                          type: string
                          description: News publication date and time
                        header:
                          type: string
                          description: News header
                        id:
                          type: integer
                          description: News ID
                        types:
                          type: array
                          description: News tags
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                description: Tag ID
                              name:
                                type: string
                                description: Tag name
              example:
                data:
                  - content: |
                      Теперь в кампаниях ВБ.Медиа вы можете размещать баннеры для пользователей, которые взаимодействовали
                      с товарами из определённой категории: покупали, искали, добавляли в корзину и избранное. Также можно
                      выбрать период, за который хотите учитывать эти действия.Например, вы продаёте обувь. Рекламу можно
                      показать людям, которые добавляли в корзину или избранное товары из этой категории за последние 14
                      дней. Возможно, пользователи, которые попадают под этот критерий, уже совершили покупку. Поэтому вы
                      можете уточнить настройки показа: добавить параметр «Не покупал товар из категории „Обувь“ в последние
                      14 дней». Так вероятность того, что ваш баннер приведёт к покупке, будет выше.Чтобы запустить рекламу,
                      создайте в кабинете ВБ.Медиа кампанию «По показам» и на шаге 4 включите «Поведенческие параметры».
                      Эти параметры можно комбинировать с таргетированием по предполагаемым интересам, полу, возрасту и
                      региону.Подробнее о том, как настроить таргетинг, — в инструкции «По показам».Запустить рекламу на
                      Wildberries
                    date: '2025-02-05T14:10:35+03:00'
                    header: |
                      Новые настройки кампаний в ВБ.Медиа: таргетируйте рекламу в зависимости от того, как аудитория
                      использует сервисы Wildberries
                    id: 7369
                    types:
                      - id: 4
                        name: Маркетинг
                  - content: |
                      Добавили получение отчётов по текстам поисковых запросов в формате CSV. В описания методов «Создать
                      отчёт» и «Получить отчёт» добавили описания и примеры моделей: • запросов — SearchReportTextReq, •
                      успешных ответов (статус-код 200) — SearchReportTextRes.В ответ метода «Поисковые запросы по товару»
                      добавили 8 полей и структуры price и medianPosition. Узнать больше можно в Журнале изменений.Эти методы
                      доступны только с подпиской «Джем»
                    date: '2025-02-06T18:14:58+03:00'
                    header: Изменения в API «Аналитики и данных»
                    id: 7373
                    types:
                      - id: 8
                        name: API
                      - id: 41
                        name: Аналитика продавца
        '400':
          description: Bad request
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
  /api/v1/seller-info:
    servers:
      - url: https://common-api.wildberries.ru
    get:
      x-readonly-method: true
      x-category: commonapi
      tags:
        - Seller Information
      security:
        - HeaderApiKey: []
      summary: Get Seller Information
      description: |
        This method allows you to obtain the seller's name and account ID.
        <br> You can use any token in request, as long as the **Test Environment** option is not selected.

        <div class="description_limit">
        <a href="/openapi/api-information#tag/Introduction/Rate-Limits">Request limit</a> per one seller's account:

        | Period | Limit | Interval | Burst |
        | --- | --- | --- | --- |
        | 1 minute | 1 request | 1 minute | 10 requests |
        </div>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Seller's name
                  sid:
                    format: UUID
                    type: string
                    description: Wildberries Seller [ID](./api-information#tag/Avtorizaciya/Kak-ustroen-token)
                  tradeMark:
                    type: string
                    description: Seller's trade name
              example:
                name: ИП Кружинин В. Р.
                sid: e8923014-e233-47q8-898e-3cc86d67ea61
                tradeMark: Flax Store
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
  /api/v1/invite:
    servers:
      - url: https://user-management-api.wildberries.ru
    post:
      tags:
        - Seller User Management
      security:
        - HeaderApiKey: []
      summary: Create an Invitation for a New User
      description: |
        The method creates an invitation for a new user with access settings to the seller account sections.<br>
        How access rights are assigned:
        - If `access` is empty (`[]`) or not provided — by default, all access is granted, except for access to the showcase (`showcase`) and **Jam** (`changeJam`)
        - If `access` specifies some of the account sections, then in addition to the access rights specified in the request, all default access rights are also granted
        - If `access` lists all possible sections, access rights will be granted according to the request, without the default access rights
        - If the same section (`code`) is specified twice in `access`:
          - with different `disabled` values (`true` and `false`), access will not be granted
          - with identical values of `"disabled": true`, access will not be granted
          - with identical values of `"disabled": false`, access will be granted

        <div class="description_limit">
        <a href="/openapi/api-information#tag/Introduction/Rate-Limits">Request limit</a> per one seller's account:

        | Period | Limit | Interval | Burst |
        | --- | --- | --- | --- |
        | 1 second | 1 request | 1 second | 5 requests |
        </div>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createInviteRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createInviteResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
  /api/v1/users:
    servers:
      - url: https://user-management-api.wildberries.ru
    get:
      tags:
        - Seller User Management
      security:
        - HeaderApiKey: []
      summary: Get a List of Seller Active or Invited Users
      description: |
        The method returns a list of seller account active or invited users.<br><br>

        Specify the value of the `isInviteOnly` parameter to select the list:
          - `isInviteOnly=true` — invited users list who have not yet activated access
          - `isInviteOnly=false` or is not provided — active users list

        For each user, you can get:
          - user's role
          - accessible sections
          - invitation status

        The list of invited users in the response is always sorted by creation date: from newest to oldest.

        <div class="description_limit">
        <a href="/openapi/api-information#tag/Introduction/Rate-Limits">Request limit</a> per one seller's account:

        | Period | Limit | Interval | Burst |
        | --- | --- | --- | --- |
        | 1 second | 1 request | 1 second | 5 requests |
        </div>
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            format: int64
            maximum: 100
            default: 100
          description: The number of active or invited users in the response
        - in: query
          name: offset
          schema:
            type: integer
            format: int64
            default: 0
          description: |
            How many results to skip. For example, for the value 10, the response will start with the 11 element
        - in: query
          name: isInviteOnly
          schema:
            type: boolean
            default: false
          description: |
            - `true` — the list of invited users who have not yet activated access
            - `false` or not provided — the list of active users of the seller account
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUsersResponse'
              examples:
                invitesOnly:
                  summary: isInviteOnly=true
                  description: List of invited users
                  value:
                    total: 2
                    countInResponse: 2
                    users:
                      - id: 0
                        role: ''
                        position: Аналитик
                        phone: '79998888888'
                        email: ''
                        isOwner: false
                        firstName: ''
                        secondName: ''
                        patronymic: ''
                        goodsReturn: false
                        isInvitee: true
                        inviteeInfo:
                          phoneNumber: '79998888888'
                          position: Аналитик
                          inviteUuid: 00000000-0000-4000-8000-000000000001
                          expiredAt: '2025-12-01T00:00:00Z'
                          isActive: true
                        access:
                          - code: supply
                            disabled: true
                          - code: changeJam
                            disabled: true
                          - code: showcase
                            disabled: false
                          - code: suppliersDocuments
                            disabled: false
                          - code: discountPrice
                            disabled: true
                          - code: feedbacks
                            disabled: false
                          - code: questions
                            disabled: false
                          - code: wbPoint
                            disabled: false
                          - code: brands
                            disabled: true
                          - code: pointsForReviews
                            disabled: false
                          - code: pinFeedbacks
                            disabled: false
                          - code: finance
                            disabled: true
                          - code: feedbacksQuestions
                            disabled: false
                          - code: balance
                            disabled: false
                      - id: 0
                        role: ''
                        position: ''
                        phone: 7999XXXX102
                        email: ''
                        isOwner: false
                        firstName: ''
                        secondName: ''
                        patronymic: ''
                        goodsReturn: false
                        isInvitee: true
                        inviteeInfo:
                          phoneNumber: '79996666666'
                          position: Аналитик
                          inviteUuid: 00000000-0000-4000-8000-000000000002
                          expiredAt: '2025-12-10T00:00:00Z'
                          isActive: false
                        access:
                          - code: supply
                            disabled: true
                          - code: changeJam
                            disabled: true
                          - code: showcase
                            disabled: false
                          - code: suppliersDocuments
                            disabled: false
                          - code: discountPrice
                            disabled: true
                          - code: feedbacks
                            disabled: false
                          - code: questions
                            disabled: false
                          - code: wbPoint
                            disabled: false
                          - code: brands
                            disabled: true
                          - code: pointsForReviews
                            disabled: false
                          - code: pinFeedbacks
                            disabled: false
                          - code: finance
                            disabled: true
                          - code: feedbacksQuestions
                            disabled: false
                          - code: balance
                            disabled: false
                usersOnly:
                  summary: isInviteOnly=false
                  description: List of active users
                  value:
                    total: 2
                    countInResponse: 2
                    users:
                      - id: 1001
                        role: user
                        position: Аналитик
                        phone: '79999999999'
                        email: user1@example.com
                        isOwner: true
                        firstName: Иван
                        secondName: Иванов
                        patronymic: ''
                        goodsReturn: true
                        isInvitee: false
                        inviteeInfo: null
                        access:
                          - code: supply
                            disabled: true
                          - code: changeJam
                            disabled: true
                          - code: showcase
                            disabled: false
                          - code: suppliersDocuments
                            disabled: false
                          - code: discountPrice
                            disabled: true
                          - code: feedbacks
                            disabled: false
                          - code: questions
                            disabled: false
                          - code: wbPoint
                            disabled: false
                          - code: brands
                            disabled: true
                          - code: pointsForReviews
                            disabled: false
                          - code: pinFeedbacks
                            disabled: false
                          - code: finance
                            disabled: true
                          - code: feedbacksQuestions
                            disabled: false
                          - code: balance
                            disabled: false
                      - id: 1002
                        role: user
                        position: Менеджер
                        phone: '79997777777'
                        email: user2@example.com
                        isOwner: false
                        firstName: Владимир
                        secondName: Смирнов
                        patronymic: ''
                        goodsReturn: true
                        isInvitee: true
                        inviteeInfo:
                          phoneNumber: '79997777777'
                          position: Менеджер
                          inviteUuid: 00000000-0000-4000-8000-000000000001
                          expiredAt: '2025-12-01T00:00:00Z'
                          isActive: true
                        access:
                          - code: supply
                            disabled: true
                          - code: changeJam
                            disabled: true
                          - code: showcase
                            disabled: false
                          - code: suppliersDocuments
                            disabled: false
                          - code: discountPrice
                            disabled: true
                          - code: feedbacks
                            disabled: false
                          - code: questions
                            disabled: false
                          - code: wbPoint
                            disabled: false
                          - code: brands
                            disabled: true
                          - code: pointsForReviews
                            disabled: false
                          - code: pinFeedbacks
                            disabled: false
                          - code: finance
                            disabled: true
                          - code: feedbacksQuestions
                            disabled: false
                          - code: balance
                            disabled: false
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
  /api/v1/users/access:
    servers:
      - url: https://user-management-api.wildberries.ru
    put:
      tags:
        - Seller User Management
      security:
        - HeaderApiKey: []
      summary: Update User's Access Permissions
      description: |
        The method changes the access rights for one or more users.<br>
        <br>
        Only the data passed in the request parameters will be updated. The other fields will remain unchanged.

        <div class="description_limit">
        <a href="/openapi/api-information#tag/Introduction/Rate-Limits">Request limit</a> per one seller's account:

        | Period | Limit | Interval | Burst |
        | --- | --- | --- | --- |
        | 1 second | 1 request | 1 second | 5 requests |
        </div>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateUserAccessRequest'
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
  /api/v1/user:
    servers:
      - url: https://user-management-api.wildberries.ru
    delete:
      tags:
        - Seller User Management
      security:
        - HeaderApiKey: []
      summary: Delete User
      description: |
        The method removes a user from [the seller user list](/openapi/api-information#tag/Seller-User-Management/paths/~1api~1v1~1users/get). This user will no longer have access to the seller account.

        <div class="description_limit">
        <a href="/openapi/api-information#tag/Introduction/Rate-Limits">Request limit</a> per one seller's account:

        | Period | Limit | Interval | Burst |
        | --- | --- | --- | --- |
        | 1 second | 1 request | 1 second | 10 requests |
        </div>
      parameters:
        - in: query
          name: deletedUserID
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the user whose access will be revoked
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    Access:
      type: array
      description: Access settings for seller account sections
      items:
        type: object
        required:
          - code
          - disabled
        properties:
          code:
            type: string
            description: |
              The code for the seller account section the user will get access to:
              * `balance` — View balance and withdraw funds
              * `brands` — Brands management
              * `changeJam` — Access to **Jam** subscription: **A/B tests**, photo tags, video autostarts, product card comparisons
              * `discountPrice` — Change product prices, manage discounts and promotions
              * `finance` — Financial analytics. Balance statistics, financial reports, payment history
              * `showcase` — Showcase management
              * `suppliersDocuments` — View and download documents related to platform operations
              * `supply` — Create and manage FBW supplies
              * `feedbacksQuestions` — Viewing and answering customer questions and reviews, complaints about reviews
              * `questions` — View and respond to customer questions
              * `pinFeedbacks` — Ability to pin and unpin reviews
              * `pointsForReviews` — Points for reviews
              * `feedbacks` — View and respond to customer reviews
              * `wbPoint` — WB Point
            enum:
              - balance
              - brands
              - changeJam
              - discountPrice
              - finance
              - showcase
              - suppliersDocuments
              - supply
              - feedbacksQuestions
              - questions
              - pinFeedbacks
              - pointsForReviews
              - feedbacks
              - wbPoint
          disabled:
            type: boolean
            description: |
              * `true` — access to the section is disabled
              * `false` — access to the section is enabled
      example:
        - code: balance
          disabled: false
        - code: pointsForReviews
          disabled: false
        - code: brands
          disabled: true
        - code: finance
          disabled: true
        - code: supply
          disabled: true
    getUsersResponse:
      type: object
      required:
        - users
        - total
        - countInResponse
      properties:
        total:
          type: integer
          description: The total number of active or invited users in the list
        countInResponse:
          type: integer
          description: The number of active or invited users on the current page
        users:
          type: array
          description: User information
          items:
            type: object
            required:
              - id
              - role
              - position
              - phone
              - email
              - isOwner
              - firstName
              - secondName
              - patronymic
              - goodsReturn
              - isInvitee
              - inviteeInfo
              - access
            properties:
              id:
                type: integer
                description: User ID
              role:
                type: string
                description: |
                  User role:
                  * `user` — user who have activated access
                  * ` ` (empty string) — user who have not yet activated access
                enum:
                  - user
                  - ''
              position:
                type: string
                description: User's position
              phone:
                type: string
                description: User's phone number
              email:
                type: string
                description: User's email
              isOwner:
                type: boolean
                description: Is the user the seller account's owner
              firstName:
                type: string
                description: User's first name
              secondName:
                type: string
                description: User's last name
              patronymic:
                type: string
                description: User's patronymic
              goodsReturn:
                type: boolean
                description: Can user approve product returns
              isInvitee:
                type: boolean
                description: Is the user invited
              inviteeInfo:
                type: object
                nullable: true
                description: Invitation information, if the user is invited
                properties:
                  phoneNumber:
                    type: string
                    description: Invited user's phone number
                  position:
                    type: string
                    description: Invited user's position
                  inviteUuid:
                    type: string
                    description: Invitation ID
                    format: UUID
                  expiredAt:
                    type: string
                    format: date-time
                    description: Invitation expiration date and time
                  isActive:
                    type: boolean
                    description: |
                      - `true` — the invitation is active
                      - `false` — the invitation is inactive
              access:
                $ref: '#/components/schemas/Access'
    createInviteRequest:
      type: object
      required:
        - invite
      properties:
        access:
          $ref: '#/components/schemas/Access'
        invite:
          type: object
          required:
            - phoneNumber
          properties:
            phoneNumber:
              type: string
              description: |
                User's phone number for the invitation.
                <details><summary><strong>Phone numbers from the following countries are supported:</strong></summary>• Armenia<br>• Azerbaijan<br>• Barbados<br>• Belarus<br>• Brazil<br>• China<br>• Czech Republic<br>• Georgia<br>• Hong Kong<br>• Italy<br>• Kazakhstan<br>• Kyrgyzstan<br>• Macau<br>• Russia<br>• Serbia<br>• Sweden<br>• Tajikistan<br>• Turkey<br>• UAE<br>• Uzbekistan</details>
            position:
              type: string
              maxLength: 150
              description: User's position
      example:
        access:
          - code: balance
            disabled: false
          - code: pointsForReviews
            disabled: false
          - code: brands
            disabled: true
          - code: finance
            disabled: true
          - code: supply
            disabled: true
        invite:
          phoneNumber: '79999999999'
          position: Менеджер
    createInviteResponse:
      type: object
      required:
        - inviteID
        - expiredAt
        - isSuccess
        - inviteUrl
      description: Invitation details
      properties:
        inviteID:
          type: string
          format: uuid
          description: Invitation ID
        expiredAt:
          type: string
          format: date-time
          description: Date and time of expiration of the invitation
        isSuccess:
          type: boolean
          description: |
            - `true` — the invitation was created successfully
            - `false` — retry the request
        inviteUrl:
          type: string
          format: uri
          description: The invitation URL that the user should follow
      example:
        inviteID: 741b8aa6-08ac-4782-8a9d-d931bcbbf608
        expiredAt: '2025-10-06T10:56:04.335060746Z'
        isSuccess: true
        inviteUrl: https://seller.wildberries.ru/supplier-settings/supplier-card?inviteId=e5a813c7-65e0-4599-a550-a6b3d85661ed
    updateUserAccessRequest:
      type: object
      required:
        - usersAccesses
      properties:
        usersAccesses:
          type: array
          description: Access settings for user
          items:
            $ref: '#/components/schemas/UserAccess'
      example:
        usersAccesses:
          - userId: 42334965
            access:
              - code: balance
                disabled: false
              - code: finance
                disabled: true
              - code: feedbacks
                disabled: false
          - userId: 52334965
            access:
              - code: balance
                disabled: true
              - code: changeJam
                disabled: false
              - code: showcase
                disabled: false
    UserAccess:
      type: object
      properties:
        userId:
          type: integer
          description: User ID
        access:
          $ref: '#/components/schemas/Access'
    errorResponse:
      type: object
      required:
        - title
        - detail
        - requestId
        - origin
        - status
      properties:
        title:
          type: string
          description: Error title
        detail:
          type: string
          description: Error details
        requestId:
          type: string
          description: Request ID
        origin:
          type: string
          description: Internal service name
        status:
          type: number
          description: HTTP status code
      example:
        title: Bad Request
        status: 400
        detail: 'bad request cause: user is not in current supplier'
        requestId: c479c04d0b576a9ba0b20fdf235004c2
        origin: public-acl
  responses:
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: Error title
              detail:
                type: string
                description: Error details
              code:
                type: string
                description: Internal error code
              requestId:
                type: string
                description: Unique request ID
              origin:
                type: string
                description: WB internal service ID
              status:
                type: number
                description: HTTP status code
              statusText:
                type: string
                description: Text of the HTTP status code
              timestamp:
                type: string
                format: date-time
                description: Request date and time
          example:
            title: unauthorized
            detail: 'token problem; token is malformed: could not base64 decode signature: illegal base64 data at input byte 84'
            code: 07e4668e--a53a3d31f8b0-[UK-oWaVDUqNrKG]; 03bce=277; 84bd353bf-75
            requestId: 7b80742415072fe8b6b7f7761f1d1211
            origin: s2s-api-auth-catalog
            status: 401
            statusText: Unauthorized
            timestamp: '2024-09-30T06:52:38Z'
    '429':
      description: Too many requests
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: Error title
              detail:
                type: string
                description: Error details
              code:
                type: string
                description: Internal error code
              requestId:
                type: string
                description: Unique request ID
              origin:
                type: string
                description: WB internal service ID
              status:
                type: number
                description: HTTP status code
              statusText:
                type: string
                description: Text of the HTTP status code
              timestamp:
                type: string
                format: date-time
                description: Request date and time
          example:
            title: too many requests
            detail: limited by c122a060-a7fb-4bb4-abb0-32fd4e18d489
            code: 07e4668e-ac2242c5c8c5-[UK-4dx7JUdskGZ]
            requestId: 9d3c02cc698f8b041c661a7c28bed293
            origin: s2s-api-auth-catalog
            status: 429
            statusText: Too Many Requests
            timestamp: '2024-09-30T06:52:38Z'
